language: ruby
rvm:
  - jruby-19mode
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - ruby-head
  - jruby-head
env:
  matrix:
    - TEST_DOC=0
    - TEST_DOC=1
install:
  - gem install bundler --version "~> 1.8"
  - bundle
script:
  - > if $TEST_DOC then; rake doc | tail -1 | ruby -e "((/\\d+.\\d+/.match readline)[0].to_f >= 80) ? (exit 0) : (exit 1)\"; else bundle exec rake spec; fi
matrix:
  exclude:
    - env: TEST_DOC=0
  include:
    - rvm: 2.2.0
      env: TEST_DOC=0