language: ruby
rvm:
  - jruby-19mode
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - ruby-head
  - jruby-head
install:
  - gem install bundler --version "~> 1.8"
  - bundle
script:
  - bundle exec rake spec