language: ruby
rvm:
  - jruby-19mode
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - ruby-head
  - jruby-head
env:
  global:
    - CI=true
  matrix:
    - TEST_DOC=false
    - TEST_DOC=true
install:
  - gem install bundler --version "~> 1.8"
  - bundle
script:
  - >
    if [[ $TEST_DOC == true ]]; then
      bundle exec rake doc_cover
    else
      bundle exec rake spec
    fi
matrix:
  exclude:
    - env: TEST_DOC=true
  include:
    - rvm: 2.2.0
      env: TEST_DOC=true