#!/usr/bin/env ruby

require 'logger'

require 'trollop'

require 'boofar'


Boofar::CLI.new ARGV

=begin
cmd = ARGV.shift
cmd_opts = case cmd
  when "new"
    Trollop::options do
      version VERSION_LINE
      banner <<-EOS
Usage:
    boofar new <site name> [options]

Creates a folder named <site name> and creates an empty site skelleton.

where [options] are
EOS

      opt :folder, "Overrides folder name, usefull when <site name> contains spaces or other special characters", type: :string
      opt :git,    "Create a git repository", type: :flag, default: true
    end
  when "deploy"
  when "build"
  when "watch"
  when ""
  when nil
  else
    Trollop::die "unknown subcommand '#{cmd.inspect}'"
  end


Trollop::educate if display_summary

puts "Global options:      #{global_opts.inspect}"
puts "Subcommand:          #{cmd.inspect}"
puts "Subcommand options:  #{cmd_opts.inspect}"
puts "Remaining arguments: #{ARGV.inspect}"
=end